# circleci build -c .circleci/config.yml --job setup_test_rspec

version: 2.1
# 複数のジョブをまたがってマシン環境を設定、使いまわせる
executors:
  rspec-executor:
    docker:
      - image: cimg/ruby:3.0.1
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
          BUNDLE_PATH: back/vendor/bundle
      - image: circleci/mysql:8.0.18-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: proto2_test
        command: mysqld --default-authentication-plugin=mysql_native_password
    working_directory: ~/proto2

jobs:
  setup_test_rspec:
    executor:
      name: rspec-executor
    steps:
      - checkout
      - restore_cache:
          name: gemキャッシュの復元
          keys:
            # path注意
            - v1-bundle-{{checksum "back/Gemfile.lock"}}
      - run:
          name: gemのインストール
          # gemfileが存在するディレクトリ内で実行する必要があるので初めにディレクトリ移動
          command: cd back && bundle check || bundle install
      - save_cache:
          name: gemキャッシュの保存
          key: v1-bundle-{{checksum "back/Gemfile.lock"}}
          paths:
            - back/vendor/bundle
      - run:
          name: データベースの起動を待機
          command: |
            dockerize -wait \
            tcp://${DB_HOST}:3306 -timeout 120s
      - run:
          name: データベースのセットアップ
          command: cd back && bundle exec rails db:schema:load --trace
      - run:
          name: Rspecを実行
          command: cd back && bundle exec rspec
workflows:
  version: 2.1
  workflow:
    jobs:
      - setup_test_rspec
